{{- if .Values.auth.GithubClientSecret -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-client-secret
spec:
  encryptedData:
    githubClientSecret: {{ .Values.auth.GithubClientSecret }}
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-client-secret
{{- end }}
